declare const styles:
  & Readonly<{ "_pl-1": string }>
  & Readonly<{ "_pl-2": string }>
  & Readonly<{ "_pl-3": string }>
  & Readonly<{ "_pl-4": string }>
  & Readonly<{ "_pl-5": string }>
  & Readonly<{ "_pl-6": string }>
  & Readonly<{ "_pl-7": string }>
  & Readonly<{ "_pl-8": string }>
  & Readonly<{ "_pl-9": string }>
  & Readonly<{ "_pl-10": string }>
  & Readonly<{ "_pr-1": string }>
  & Readonly<{ "_pr-2": string }>
  & Readonly<{ "_pr-3": string }>
  & Readonly<{ "_pr-4": string }>
  & Readonly<{ "_pr-5": string }>
  & Readonly<{ "_pr-6": string }>
  & Readonly<{ "_pr-7": string }>
  & Readonly<{ "_pr-8": string }>
  & Readonly<{ "_pr-9": string }>
  & Readonly<{ "_pr-10": string }>
  & Readonly<{ "_pt-1": string }>
  & Readonly<{ "_pt-2": string }>
  & Readonly<{ "_pt-3": string }>
  & Readonly<{ "_pt-4": string }>
  & Readonly<{ "_pt-5": string }>
  & Readonly<{ "_pt-6": string }>
  & Readonly<{ "_pt-7": string }>
  & Readonly<{ "_pt-8": string }>
  & Readonly<{ "_pt-9": string }>
  & Readonly<{ "_pt-10": string }>
  & Readonly<{ "_pb-1": string }>
  & Readonly<{ "_pb-2": string }>
  & Readonly<{ "_pb-3": string }>
  & Readonly<{ "_pb-4": string }>
  & Readonly<{ "_pb-5": string }>
  & Readonly<{ "_pb-6": string }>
  & Readonly<{ "_pb-7": string }>
  & Readonly<{ "_pb-8": string }>
  & Readonly<{ "_pb-9": string }>
  & Readonly<{ "_pb-10": string }>
  & Readonly<{ "_px-1": string }>
  & Readonly<{ "_px-2": string }>
  & Readonly<{ "_px-3": string }>
  & Readonly<{ "_px-4": string }>
  & Readonly<{ "_px-5": string }>
  & Readonly<{ "_px-6": string }>
  & Readonly<{ "_px-7": string }>
  & Readonly<{ "_px-8": string }>
  & Readonly<{ "_px-9": string }>
  & Readonly<{ "_px-10": string }>
  & Readonly<{ "_py-1": string }>
  & Readonly<{ "_py-2": string }>
  & Readonly<{ "_py-3": string }>
  & Readonly<{ "_py-4": string }>
  & Readonly<{ "_py-5": string }>
  & Readonly<{ "_py-6": string }>
  & Readonly<{ "_py-7": string }>
  & Readonly<{ "_py-8": string }>
  & Readonly<{ "_py-9": string }>
  & Readonly<{ "_py-10": string }>
;
export default styles;
//# sourceMappingURL=./_margin.module.scss.d.ts.map
