declare const styles:
  & Readonly<{ "_ml-1": string }>
  & Readonly<{ "_ml-2": string }>
  & Readonly<{ "_ml-3": string }>
  & Readonly<{ "_ml-4": string }>
  & Readonly<{ "_ml-5": string }>
  & Readonly<{ "_ml-6": string }>
  & Readonly<{ "_ml-7": string }>
  & Readonly<{ "_ml-8": string }>
  & Readonly<{ "_ml-9": string }>
  & Readonly<{ "_ml-10": string }>
  & Readonly<{ "_mr-1": string }>
  & Readonly<{ "_mr-2": string }>
  & Readonly<{ "_mr-3": string }>
  & Readonly<{ "_mr-4": string }>
  & Readonly<{ "_mr-5": string }>
  & Readonly<{ "_mr-6": string }>
  & Readonly<{ "_mr-7": string }>
  & Readonly<{ "_mr-8": string }>
  & Readonly<{ "_mr-9": string }>
  & Readonly<{ "_mr-10": string }>
  & Readonly<{ "_mt-1": string }>
  & Readonly<{ "_mt-2": string }>
  & Readonly<{ "_mt-3": string }>
  & Readonly<{ "_mt-4": string }>
  & Readonly<{ "_mt-5": string }>
  & Readonly<{ "_mt-6": string }>
  & Readonly<{ "_mt-7": string }>
  & Readonly<{ "_mt-8": string }>
  & Readonly<{ "_mt-9": string }>
  & Readonly<{ "_mt-10": string }>
  & Readonly<{ "_mb-1": string }>
  & Readonly<{ "_mb-2": string }>
  & Readonly<{ "_mb-3": string }>
  & Readonly<{ "_mb-4": string }>
  & Readonly<{ "_mb-5": string }>
  & Readonly<{ "_mb-6": string }>
  & Readonly<{ "_mb-7": string }>
  & Readonly<{ "_mb-8": string }>
  & Readonly<{ "_mb-9": string }>
  & Readonly<{ "_mb-10": string }>
  & Readonly<{ "_mx-1": string }>
  & Readonly<{ "_mx-2": string }>
  & Readonly<{ "_mx-3": string }>
  & Readonly<{ "_mx-4": string }>
  & Readonly<{ "_mx-5": string }>
  & Readonly<{ "_mx-6": string }>
  & Readonly<{ "_mx-7": string }>
  & Readonly<{ "_mx-8": string }>
  & Readonly<{ "_mx-9": string }>
  & Readonly<{ "_mx-10": string }>
  & Readonly<{ "_my-1": string }>
  & Readonly<{ "_my-2": string }>
  & Readonly<{ "_my-3": string }>
  & Readonly<{ "_my-4": string }>
  & Readonly<{ "_my-5": string }>
  & Readonly<{ "_my-6": string }>
  & Readonly<{ "_my-7": string }>
  & Readonly<{ "_my-8": string }>
  & Readonly<{ "_my-9": string }>
  & Readonly<{ "_my-10": string }>
;
export default styles;
//# sourceMappingURL=./_padding.module.scss.d.ts.map
