# https://github.com/oikwsat/jest-sample/blob/main/.github/workflows/jest-coverage-report.yml
# https://oikawa.dev/blog/20210810_jest-coverage-report-action
name: Jest coverage report

on:
  workflow_dispatch:
  push:
  pull_request:

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: write-all

jobs:
  jest-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout projects'
        uses: actions/checkout@v2
      - name: 'Install packages'
        run: npm install
      - name: Jest coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: npm
          test-script: npm run coverage:ci
          #   threshold: 80 # optional parameter
      - name: Analyze bundle sizes
        uses: transferwise/actions-next-bundle-analyzer@v2
        with:
          # Optional, specifies where to look for .next folder. Defaults to cwd.
          # working-directory: ./apps/my-next-app
          # Optional, configures commenting strategy around insignificant changes, defaults to `always`.
          # Available options:
          #   always: Always comment on PRs, even if it's just to say there are no significant changes.
          #   skip-insignificant: Skip commenting on PRs if there are no signficant changes in page sizes.
          comment-strategy: 'always'
          # Optional, configures whether to create the bundle size summary issue, defaults to `true`.
          # Available options:
          #   true
          #   false
          create-issue: true
          # Optional, defaults to `github.token`.
          # github-token: ${{ github.token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
